# Generated by cucumber-sinatra. (2016-12-10 13:50:30 -0800)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'recipe.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Recipe

class TestWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  TestWorld.new
end
